### ISSUE TITLE
RPM default file name should be with "." instead of "-" before the <arch>

### ISSUE THREAD

**Issue by yarix** [eclipse/packagedrone#123]
the RPM file name format should be:
`<name>-<version>-<release>.<architecture>.rpm`
(here http://ftp.rpm.org/max-rpm/ch-rpm-file-format.html or https://en.wikipedia.org/wiki/Rpm_(software)) 

however the current makeDefaultFileName() uses "-" instead of the "." before the architecture.
   ```
private String makeDefaultFileName ()
    {
        final StringBuilder sb = new StringBuilder ( RpmLead.toLeadName ( this.name, this.version ) );
        sb.append ( '-' ).append ( this.architecture ).append ( ".rpm" );
        return sb.toString ();
    }
```

**Comment by ctron** [comment]
Hi @yarix … thanks for the PR. I do agree with the change in general and I would definitely like to bring this in.

There are two things which I would like you to consider in the change:
1. Please add yourself to the copyright header and be sure to have signed the [ECA](https://www.eclipse.org/legal/ECA.php). Let me know if you need any help with this.
1. Currently people using this functionality might expect to name to be generated like this. So I think it would be best to make this configurable. Like setting a "default name provider" which can be set in order to override the current behavior. Or replaced altogether with a custom implementation.
   The default  for now should be the current naming. With the option to override this. In the major next version we should switch this. So that you have the new behavior as default and switch to the legacy one manually.

What do you think?!

**Comment by toomyem** [comment]
I would be happy to see this fixed, this or the other way (preferably with customization). Workaround from https://github.com/ctron/rpm-builder/issues/24 makes handling snapshots quite difficult.

**Comment by yarix** [comment]
hi @ctron 
1. signed the ECA
2. Yes, I agree with making it configurable. 
3. I need help in building the environment for development and testing. i followed https://wiki.eclipse.org/PackageDrone/HowTo/Contribute building with oomph but eclipse still have lots of errors. is there a better guide?

**Comment by yarix** [comment]
Hi @ctron ,
i made PR #126, to address your comments.

**Comment by ctron** [comment]
I think this is actually fixed a while back now. Please re-open otherwise.
